name: test

on:
  workflow_dispatch:

jobs:
  EnvA:
    name: Env A
    runs-on: ubuntu-latest
    environment: A
    env:
      SECRET: "${{ secrets.SECRET }}"
      VARIABLE: "${{ env.VARIABLE }}"
    steps:
      - name: Mis
        run: env
  EnvB:
    name: Env B
    runs-on: ubuntu-latest
    environment: B
    env:
      SECRET: "${{ secrets.SECRET }}"
      VARIABLE: "${{ env.VARIABLE }}"
    steps:
      - name: Mis
        run: env
